### ISSUE TITLE
Duplicate product on SciHub causes sentinelsat download to freeze

### ISSUE THREAD

**Issue by justinkotzebue** [sentinelsat/sentinelsat#125] opened 2017-06-07 09:32 UTC
When I attempt to download S2A_MSIL1C_20170205T105221_N0204_R051_T31TCF_20170205T105426, which exists twice on SciHub

- https://scihub.copernicus.eu/dhus/odata/v1/Products('2f379a52-3041-4b92-a8a8-92bddc495594')/$value
- https://scihub.copernicus.eu/dhus/odata/v1/Products('10762fc0-461d-48d7-ad93-7ce71af9bd1a')/$value

the product (probably in one of the two versions) is downloaded correctly. But afterwards, the download freezes at 0%.

**Comment by j08lue** [comment] 2017-06-07 09:52
We notice quite often that SciHub publishes products multiple times, where the first release is faulty (data all NaN or missing files) and the second is a fixed version. Mostly with slightly different production time stamps, so there are no issues with downloading both.

In this case, however, the production times are identical. The downloader finds the existing file name and freezes.

This will be very easy to demonstrate once we have the `--title` option from https://github.com/sentinelsat/sentinelsat/issues/115. But I will make a test example too.

**Comment by Fernerkundung** [comment] 2017-06-07 12:14
@justinkotzebue In the case of two non-identical products with identical (file)names what would you expect as behaviour? An error message, both downloaded and renamed with appendixes, a kind of check if one of them is faulty?

I'm a bit stumped by this behaviour of the OpenAccessHub, since, in theory, products with the same sensing and production timestamps (hence the identical filenames) should be identical in content. Therefore it shouldn't matter which one `sentinelsat` downloads. Your example however clearly demonstrates that there are faulty products published under identical filenames.

**Comment by j08lue** [comment] 2017-06-07 13:17
Checking for faults would be nice, but that would be very heuristic (guessing at files that should be there, ...) or heavy (checking for all-NaN files). Checksums obviously do not help here, because the they are generated from the released products on server side as well as on client side and are therefore identical even for faulty releases.

It would be quite cool if `sentinelsat` could remove duplicates already in the OpenAccessHub results based on identical **granule(s)** and **sensing time** (i.e. ignoring the production time). Like with an option `--deduplicate-method latest`. Sure, users can do that after the download, but that means they already pulled a lot of unusable data. But would that become too automagic?

**Comment by Fernerkundung** [comment] 2017-06-07 13:20
> they already pulled a lot of unusable data

Any examples how often duplicate products with identical filenames actually appear? Until shown otherwise my feeling is this is more of an edge case where some kind of error message would suffice.

**Comment by j08lue** [comment] 2017-06-07 13:44
Yes, this was the first time we experienced completely identical file names. I meant also to "de-duplicate" those cases where the production times differ. We saw a number of those in the last months.

But you are right, this is perhaps too specific an issue for `sentinelsat` to cover. In the above case, @justinkotzebue solved it by cancelling the frozen download and starting a new query after that date.

**Comment by valgur** [comment] 2017-06-08 13:25
I'm surprised at the freezing part, not so much that the server-side duplicates are causing issues, unfortunately. I'll try to reproduce the freezing issue on my machine.

Since duplicate products are an obvious source of issues, we should consider adding some kind of de-duplication procedure to `download_all()`. Such as always trying to download just the most recently uploaded product among the duplicates.

**Comment by Fernerkundung** [comment] 2017-06-08 14:17
FWIW I can replicate the freezing issue on Win7_x64 as well as Ubuntu 16.04 using Python 3.6 and sentinelsat v0.11 with the following minimal example:

```
from sentinelsat import SentinelAPI
api = SentinelAPI('user', 'password')
duplicates = ['2f379a52-3041-4b92-a8a8-92bddc495594', '10762fc0-461d-48d7-ad93-7ce71af9bd1a']
api.download_all(duplicates)
```

The freeze also happens when I try to download any product that is already present in the download folder. This bug seems to be affecting more than just duplicate products.

> Such as always trying to download just the most recently uploaded product among the duplicates.

Going by the `Ingestion Date` you mean? That is the only meaningful difference I can find in the product dictionaries.

```
first = api.get_product_odata(duplicates[0], full=True)
second = api.get_product_odata(duplicates[1], full=True)
diffkeys = [k for k in first if first[k] != second[k]]
for k in diffkeys:
  print(k, ':', first[k], '->', second[k])
```

Then we would assume that the newer product (by ingestion, not production) is the non-faulty one. I suspect there might also be cases where both products are valid but still contain differences. Whatever we decide to do - we should always raise a warning to the user that they need to check both datasets for faults.

**Comment by j08lue** [comment] 2017-06-08 14:23
Can we quickly agree on the terminology here, @Fernerkundung - what is **ingestion time** vs. **production time**?

I was referring to production time as the time when the **final product** is made. But that is perhaps wrong terminology?

**Comment by Fernerkundung** [comment] 2017-06-08 14:30
You are right, it is important to get a clear vocabulary on this:

According to the [product naming convention](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/naming-convention) the filename contains two dates:

- **creation date** what I referred to as **production date**: When the L1C product is *created* from raw data at one of the ground segments
- **sensing time**: When the satellite acquired the image.

The metadata of DHuS then contains a third date:
- **ingestion date**: when the L1C product was uploaded, *ingested* into the DHuS

**Comment by valgur** [comment] 2017-06-08 14:49
Thanks a lot for replicating this, @Fernerkundung! 👍 It's surprising that this happens whenever a product already exists on disk. This situation should be covered by unit tests, but I guess they might be missing some relevant asserts.

> Then we would assume that the newer product (by ingestion, not production) is the non-faulty one - which is a bit of a stretch. I suspect there might also be cases where both products are valid but still contain differences. Whatever we decide to do - we should always raise a warning to the user that they need to check both datasets for faults.
Doing anything systematic would be better than the current situation where `sentinelsat` will simply try to download the product twice and in random order. It does not have to be perfect. We should definitely notify the user with a warning message, I agree. It would be the user's responsibility to do something more clever for deduplication, if that solution is not good enough.

**Comment by Fernerkundung** [comment] 2017-06-08 14:53
> Doing anything systematic would be better than the current situation where sentinelsat will simply try to download the product twice and in random order. It does not have to be perfect. We should definitely notify the user with a warning message

I completely agree! Doing something systematic and informing the user is a perfect implementation of Zen of Python, line 2 *Explicit is better than implicit.*

**Comment by valgur** [comment] 2019-04-09 06:43
I think we should look take a look at the product files listed on SciHub and check if this issue is still relevant. In my experience the duplicate products were eliminated from SciHub already more than a year or two ago.

**Comment by Fernerkundung** [comment] 2019-04-09 07:48
Any chance we can get feedback of the Copernicus Supports teams on that? Otherwise I would close it for now as I can't reproduce the issue with the example duplicates we had.

**Comment by j08lue** [comment] 2019-04-09 10:40
I have not experienced this issue since. So let us just close this and see if this ever surfaces again.

**Closed by j08lue** 2019-04-09 10:40 UTC
Labels: bug
