### ISSUE TITLE
TqdmKeyError: "Unknown argument(s): {'delay': 2}"

### ISSUE THREAD

**Issue by erickfaria** [sentinelsat/sentinelsat#548] opened 2021-11-11 12:45 UTC
Hello,

I'm using this code to download images from a footprint:

```
footprint = 'POLYGON((-56.09865992094881 -12.180375404336985,-56.123646091788004 -12.974677176821714,-55.00997201665299 -12.936412307539413,-54.9921246739596 -12.148971474168775,-56.09865992094881 -12.180375404336985,-56.09865992094881 -12.180375404336985))'
api = SentinelAPI('user', 'password', 'https://scihub.copernicus.eu/dhus')
products = api.query(footprint,
                     date=('20201106', '20211108'),
                     platformname='Sentinel-2',
                     processinglevel = 'Level-2A',
                     limit=10,
                     cloudcoverpercentage=(0, 30))

api.download_all(products, directory_path='geospatial-data/NDVI/images')
```

I'm getting the following error:

> ---------------------------------------------------------------------------
> TqdmKeyError                              Traceback (most recent call last)
> <ipython-input-36-9d2519aae086> in <module>
>       8                      cloudcoverpercentage=(0, 30))
>       9 
> ---> 10 api.download_all(products,directory_path='geospatial-data/NDVI/images')
> 
> /opt/conda/lib/python3.7/site-packages/sentinelsat/sentinel.py in download_all(self, products, directory_path, max_attempts, checksum, n_concurrent_dl, lta_retry_delay, fail_fast, nodefilter)
>     708             downloader.lta_retry_delay = lta_retry_delay
>     709         downloader.node_filter = nodefilter
> --> 710         statuses, exceptions, product_infos = downloader.download_all(products, directory_path)
>     711 
>     712         # Adapt results to the old download_all() API
> 
> /opt/conda/lib/python3.7/site-packages/sentinelsat/download.py in download_all(self, products, directory)
>     265 
>     266         statuses, online_prods, offline_prods, product_infos, exceptions = self._init_statuses(
> --> 267             product_ids
>     268         )
>     269 
> 
> /opt/conda/lib/python3.7/site-packages/sentinelsat/download.py in _init_statuses(self, product_ids)
>     385         # Get online status and product info.
>     386         for pid in self._tqdm(
> --> 387             iterable=product_ids, desc="Fetching archival status", unit="product", delay=2
>     388         ):
>     389             assert isinstance(pid, str)
> 
> /opt/conda/lib/python3.7/site-packages/sentinelsat/sentinel.py in _tqdm(self, **kwargs)
>     971         """tqdm progressbar wrapper. May be overridden to customize progressbar behavior"""
>     972         kwargs.update({"disable": not self.show_progressbars})
> --> 973         return tqdm(**kwargs)
>     974 
>     975     def get_stream(self, id, **kwargs):
> 
> /opt/conda/lib/python3.7/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
>     195 
>     196         if check_delay and self.delay > 0 and not self.displayed:
> --> 197             display(self.container)
>     198             self.displayed = True
>     199 
> 
> /opt/conda/lib/python3.7/site-packages/tqdm/std.py in __init__(self, iterable, desc, total, leave, file, ncols, mininterval, maxinterval, miniters, ascii, disable, unit, unit_scale, dynamic_ncols, smoothing, bar_format, initial, position, postfix, unit_divisor, write_bytes, lock_args, gui, **kwargs)
>     946         write_bytes  : bool, optional
>     947             If (default: None) and `file` is unspecified,
> --> 948             bytes will be written in Python 2. If `True` will also write
>     949             bytes. In all other cases will default to unicode.
>     950         lock_args  : tuple, optional
> 
> TqdmKeyError: "Unknown argument(s): {'delay': 2}"

I've updated tqdm but the problem persists.

Has anyone had this error?

When I download an image, the error doesn't appear. Only when I use download_all

Thank you all

**Comment by valgur** [comment] 2021-11-22 21:07
There appears to be a problem with your Python environment somewhere. My guess is that you updated tqdm but did not restart your notebook kernel. The code printed by the stack trace does not match the statement that raised the error, which appears to instead be from [this commit](https://github.com/tqdm/tqdm/blob/820115a8dfef27b5da12aa089d17d43828f8b168/tqdm/std.py#L948) from tqdm v4.44. Anyway, I'm closing this as the problem is not related to sentinelsat.

**Closed by valgur** 2021-11-22 21:07 UTC
