### ISSUE TITLE
500 Internel Server Error

### ISSUE THREAD

**Issue by Kay0777** [sentinelsat/sentinelsat#484] opened 2021-05-24 10:36 UTC
sentinelsat.sentinel.SentinelAPIError: HTTP status 500 Internal Server Error: UnsupportedOperationException : Error creating stream from file /mnt/s2bl2a/dhus/incoming/x1/x7/x4/S2B_MSIL2A_20210515T063629_N0300_R120_T41TMF_20210515T093145.zip.

Sometimes I get an error like this. Could you solve this error? I know that it is not your error. But it is not giving work.

Thanks!

**Comment by j08lue** [comment] 2021-05-25 07:40
> I know that it is not your error

Correct. 😄 Please report this to eosupport@copernicus.esa.int

**Comment by valgur** [comment] 2021-05-25 08:16
Server-side issue and a duplicate of #483. Closing.

**Closed by valgur** 2021-05-25 08:16 UTC
Labels: scihub-issue
