### ISSUE TITLE
BadZipfile

### ISSUE THREAD

**Issue by pandagud** [sentinelsat/sentinelsat#501] opened 2021-06-18 09:07 UTC
Hallo, I've recently upgrade to version 1.0.1 and im running into a Badzipefile problem from time to time.
The concrete product is :
```
S2B_MSIL2A_20201002T090719_N0214_R050_T35TMH_20201002T113443
```

And all downloading information is as followers: 

```
Downloading: 100%|█████████████████████████| 17.8M/17.8M [00:08<00:00, 2.16MB/s]
MD5 checksumming: 100%|█████████████████████| 17.8M/17.8M [00:00<00:00, 385MB/s]
I0618 09:02:39.833429 140156128220992 downloader.py:191] Downloaded: {'aed083e2-6f6f-4da4-8e6c-2d40f3bcf120': {'id': 'aed083e2-6f6f-4da4-8e6c-2d40f3bcf120', 'title': 'S2B_MSIL2A_20201002T090719_N0214_R050_T35TMH_20201002T113443', 'size': 17753209, 'md5': 'dbd6ee307b85a02d3f73b7fe445e5108', 'date': datetime.datetime(2020, 10, 2, 9, 7, 19, 24000), 'footprint': 'POLYGON((25.7656944498199 43.346194685301704,27.1204336460534 43.352791985217806,27.118527220871464 42.364010656318975,25.785227256908993 42.35763630855867,25.7656944498199 43.346194685301704))', 'url': "https://scihub.copernicus.eu/dhus/odata/v1/Products('aed083e2-6f6f-4da4-8e6c-2d40f3bcf120')/$value", 'Online': True, 'Creation Date': datetime.datetime(2020, 10, 2, 20, 1, 16, 378000), 'Ingestion Date': datetime.datetime(2020, 10, 2, 20, 0, 1, 364000), 'quicklook_url': "https://scihub.copernicus.eu/dhus/odata/v1/Products('aed083e2-6f6f-4da4-8e6c-2d40f3bcf120')/Products('Quicklook')/$value", 'path': '/workspace/DSD_paper_2020/SentinelProc/app/data/zipfiles/S2B_MSIL2A_20201002T090719_N0214_R050_T35TMH_20201002T113443.zip', 'downloaded_bytes': 17753209}}
I0618 09:02:39.833917 140156128220992 downloader.py:192] Triggered: {}
I0618 09:02:39.834231 140156128220992 downloader.py:193] failed: {}
```

Im using the download.all() function from the api 

And when i try to unzip the file i get the exception : `BadZipfile for product S2B_MSIL2A_20201002T090719_N0214_R050_T35TMH_20201002T113443`

If i try and manually and unzip the file Winrar gives me the following error : Unexpected end of archive

**Comment by Fernerkundung** [comment] 2021-06-18 09:30
Have you tried downloading this file manually through the web-interface and unzip it them? From time to time products are corrupted on the server side and there is nothing we can do from the `sentinelsat` side to change that.

**Comment by j08lue** [comment] 2021-06-18 11:13
Getting tons of those recently. Please tell eosupport@copernicus.esa.int with the concrete product IDs.

**Comment by avalentino** [comment] 2021-07-03 15:24
According to https://scihub.copernicus.eu/news/News00898 this should be fixed now.
Can anyone confirm?

**Comment by jlandmann** [comment] 2021-07-06 10:41
Carefully spoken: I have downloaded some L2A images over Switzerland from June this year now, and, apart from quite some failed downloads because of invalid checksums, those that are downloaded correctly now don't seem to be corrupt anymore. But, please, if anyone else can confirm as well...

**Comment by avalentino** [comment] 2021-07-06 11:54
Thanks @jlandmann.
AFAIK the issue should impact mostly products retrieved form the LTA, was that the case for your test?

**Comment by jlandmann** [comment] 2021-07-06 12:18
Oh, so true, sorry! It's been a while I haven't worked on it, now it turns out ;-)
I am trying LTA ones now, but of course the triggering takes a while (and the current download is super slow, but maybe our machine...). Will post again once I have a result.

**Comment by jlandmann** [comment] 2021-07-08 06:32
Okay, I have downloaded some from June 2018 and indeed it looks they are all good :-)

**Comment by avalentino** [comment] 2021-07-08 12:19
Thanks a lot @jlandmann.

I suppose that the issue con be closed then.

**Comment by jlandmann** [comment] 2021-07-08 13:00
I hope so. I have restarted my LTA retrieval pipeline now, but of course it takes time to test a larger number of files. Maybe you can still close since the issue is also officially declared as solved, and if people experience errors again, the issue can be reopened.

**Closed** 2021-07-08 13:21 UTC
Labels: scihub-issue
