### ISSUE TITLE
[feature request] Show quicklook images

### ISSUE THREAD

**Issue by Schlump** [sentinelsat/sentinelsat#180] opened 2017-12-16 21:00 UTC
I'm not sure if a feature like this exceeds the scope of this project,
but i personally needed an option to view the quicklooks of queried tiles.

I'm using something like this:

```
from PIL import Image
import io
def show_quicklook(id_,username,password):
      url = 
      "https://scihub.copernicus.eu/apihub/odata/v1/Products('{}')/Products('Quicklook')/$value".format(id_)
      bytes_img = requests.session().get(url, auth=(username,password)).content
      return Image.open(io.BytesIO(bytes_img))

```
Of course a caveat is that it's only useful if the query size is not huge.

**Comment by j08lue** [comment] 2017-12-17 19:42
Interesting feature. I would not say it is completely out of scope, since the quicklooks are a very high-level feature of the web-front-end to DHuS, which `sentinelsat` is just another client for.

I have tried, too, to dig into the XML tree the API provides and pull selected files from deep into the SAFE structure, but find the server terribly slow when resolving the links (many seconds of latency). But the quicklook links do not have to be constructed dynamically, it seems.

Can you make a benchmark, @Schlump, creating a larger set of quicklook links and timing them? Please use product IDs you have not queried yet, because the servers seems to cache the queries. And what is your experience with latency when running the quite neat function you made? Would this work for downloading quicklooks for like 100 products or does each link take several seconds to get resolved?

**Comment by Schlump** [comment] 2017-12-17 20:35
```
tiles = ['33VUC', '33UUB','32VUC','32UUB']

query_kwargs = {
        'platformname': 'Sentinel-2',
        'producttype': 'S2MSI1C',
        'date': ('NOW-180DAYS', 'NOW')}

products = OrderedDict()
for tile in tiles:
    kw = query_kwargs.copy()
    kw['tileid'] = tile  # products after 2017-03-31
    pp = api.query(**kw)
    products.update(pp)
    
gdf = api.to_geodataframe(products)

%%t -n3
for id_, row in gdf.iloc[0:100].iterrows():

    show_quicklook(id_,username,password)
    
```
timed with jupyter magic %timeit
25.7 s ± 4.91 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by j08lue** [comment] 2017-12-18 07:30
> 25.7 s ± 4.91 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

Quick action, @Schlump. So that was 25s for 100 quicklooks?

**Comment by Fernerkundung** [comment] 2017-12-18 11:48
How about adding the quicklook URLs to the metadata dict for each product?

This would enable a user to display them as they please by parsing the dict or (geo)dataframeand using PIL, matplotlib, GDAL or any library they fancy for display. This way we don't have to decide on which library to include as optional dependency, since there are a lot of capable image display options out there.

Furthermore we could add a CLI option like `--quicklook` which would download the qicklook images of the query. Might be useful for someone who wants to harve a look through them before using `--download` to download large datasets.

**Comment by Schlump** [comment] 2017-12-18 17:15
As a user, that's actually the way to go imho, having the urls easily accessible.

**Comment by Schlump** [comment] 2017-12-18 17:44
Well from a user perspective, it's never wrong to add the quicklook url to the metadata, but i don't really see a benefit from that, because whether i parse the id's or the actual links for displaying the Images i don't really mind ;). 

For me the question is more like if this project wants to integrate a function for easy download / viewing of quicklooks or not ;)

**Comment by j08lue** [comment] 2017-12-18 18:21
I am against adding another (optional) dependency, especially a big one like `PIL` / `pillow`.

> Furthermore we could add a CLI option like --quicklook which would download the qicklook images of the query. Might be useful for someone who wants to harve a look through them before using --download to download large datasets.

For downloading, can we just write the data to a file or do we need `PIL` to save it as valid PNG or JPEG? I would support the downloading option for the CLI and links in the metadata. Then we can leave it up to users to build viewers or the like around it.

**Comment by Schlump** [comment] 2017-12-18 18:48
For downloading afaik there's no additional library needed. The code function i used was written for storing the quicklook in memory and displaying it immediately. 

For downloading a simple function like:

```
def downlod_quicklook(id_,username,password):
	url = "https://scihub.copernicus.eu/apihub/odata/v1/Products('{}')/Products('Quicklook')/$value".format(id_)
    bytes_img = requests.session().get(url, auth=(username,password)).content
    if type(bytes_img) != bytes:
    	break
    write_image = open(id_+'quicklook.jpg', 'wb') 
    write_image.write(bytes_img) 
    write_image.close()
```


without additional dependencies would be enough.

**Comment by valgur** [comment] 2020-07-25 09:42
Closing this one as a duplicate of #361.

**Closed by valgur** 2020-07-25 09:42 UTC
Labels: discussion, enhancement
