### ISSUE TITLE
"Full authentication is required to access this resource"

### ISSUE THREAD

**Issue by ibaris** [sentinelsat/sentinelsat#73] opened 2016-12-03 19:21 UTC
Hello,

if I try to code a query (python API), I got the error message: 

> SentinelAPIError: # HTTP Status 401 - Full authentication is required to access this resource
> * * *
> **type** Status report
> **message** _Full authentication is required to access this resource_
> **description** _This request requires HTTP authentication._
> * * *
> ### Apache Tomcat/7.0.47 

However, I´m sure that my username and password are correct. 

If I try to search a sentinel scene with the command line, I got the error message: 

> Traceback (most recent call last):[...]
> sentinelsat.sentinel.SentinelAPIError: (HTTP status: 500, code: None)
> # HTTP Status 500 - Server returned HTTP response code: 400 for URL: [...]
> * * *
> **type** Exception report
> **message** _Server returned HTTP response code: 400 for URL: [...]
> **description** _The server encountered an internal error that prevented it from fulfilling this request._
> **exception**
> java.io.IOException: Server returned HTTP response code: 400 for URL: [...]
> **note** _The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs._

Here is the script for the Python API:
```
from sentinelsat.sentinel import SentinelAPI, get_coordinates
from datetime import date
import os

api = SentinelAPI('xxx', 'yyy', 'https://scihub.copernicus.eu/dhus/')

WORKDIR    = "C:\...\test"
geofile =  WORKDIR + os.sep + os.listdir(WORKDIR)[0]

# search by polygon, time, and SciHub query keywords

api.query(get_coordinates(geofile), \
          "20151219", date(2015, 12, 29), \
          keywords={"platformname": "Sentinel-1"})
```

Here is the script for the command line:
```
sentinel search -f -s 20140101 -e 20151004 -q "producttype=GRD" -u "https://scihub.copernicus.eu/dhus/" xxx yyy C:\\...\\map.geojson
```

What am I doing wrong?

**Comment by valgur** [comment] 2016-12-04 11:26
Are your user name and password correct? The examples you provided worked fine for me as long as I use my normal credentials, but when I intentionally uses incorrect ones I got the exact same errors as you did. Does searching the Data Hub work in a browser for you?

With that said, I think we should improve the error message for incorrect credentials (at least for the command line script), since the default server response is a bit vague.

**Comment by ibaris** [comment] 2016-12-04 19:00
Hello Valgut,

thank you very much for your reply. I am sure that my username and password were correct. This is really weird that the script worked with your credentials. Is it possible that my geojson file are incorrect? Which Spatial reference system should I use?

**Comment by valgur** [comment] 2016-12-04 19:21
I used the `tests/map.geojson` found in the repo to test that query.  The map file seems unlikely to me to unlikely to be the cause of your problem, though.

In my earlier message I only tested the command line bit you posted. I now took a look at the Python code you posted as well. It generates a server-side error for me as well, but the error message is the one you said you're getting on the command line.
That problem is easy to fix, though. You weren't using the keyword arguments to `query()` quite correctly. If you change that part to
```python
api.query(get_coordinates(geofile), \
           "20151219", date(2015, 12, 29), \
           platformname="Sentinel-1")
```
it should work correctly.

Does that change fix the problem for you?

**Comment by Fernerkundung** [comment] 2016-12-05 12:40
Your usage of query follows the documentation. Unfortunately our docs are wrong in that regard at the moment - see #72

**Comment by wassname** [comment] 2017-01-09 08:26
This isn't a problem with sentinelsat. I have a new login that works on the dhus api when using [the dhus script](https://scihub.copernicus.eu/twiki/do/view/SciHubUserGuide/5APIsAndBatchScripting#dhusget_script). But it doesn't work on the apihub endpoint. You can test this without sentinelsat by going to [here](https://scihub.copernicus.eu/apihub/search?).

Perhaps it takes few days for new logins to work on the apihub api. If so I should be able to report back soon.

**Comment by Fernerkundung** [comment] 2017-01-25 07:22
@wassname can you confirm that the syncing of accounts between the `dhus` and `apihub` endpoints worked after a few days?

@ibaris does the issue still occur?

**Comment by ibaris** [comment] 2017-01-25 10:26
Hello,

sorry for my late reply. I solved the problem a little bit different. I wrote a python script to execute the commands in cmd:

```
#` -*- coding: utf-8 -*-
"""
Created on Sat Dec 03 16:46:49 2016

@author: ibari
"""

import os, subprocess, time
# ----------------------------------------------------------------------
# global variables
AOI    = "~\\sentisat\\AOI"
WORKDIR    = "~\\sentisat"
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Environmental Options
username = 'xxx' 
password = 'yyy'

# blank field or *	returns all products in the archive
# Scene Options
start_date = '20140101' # Start date of the query in the format YYYYMMDD.
end_date = '20151004' # End date of the query in the format YYYYMMDD.
download = False # If True download all results of the query. If False save the footprint file

# Product Options
cloud = '40' # Maximum cloud cover
# ----------------------------------------------------------------------
# Initialise geojson files
geofile =  os.listdir(AOI)
t0      = time.time()
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# Run Command
for file in geofile:
    
    cmd = ['sentinel', 'search', '-d' if download == True else '-f', '-s',  start_date, '-e', end_date, '-p', WORKDIR,
           '--sentinel2', '--cloud', cloud,
           str(username), str(password), AOI + os.sep + file
          ]
    try:
        subprocess.call(cmd, shell=True)
    
    except Exception, e:
        xxx
       yyy
```
Now you can run this script directly from the windows cmd.

**Comment by wassname** [comment] 2017-01-26 02:06
It works now with the same credentials that failed before. So I can confirms that it takes a few days for a new login to be pushed to the apihub server.

**Comment by Fernerkundung** [comment] 2017-01-26 11:42
Thanks for the feedback @wassname and @ibaris.

I suppose this issue is solved and can be closed by @willemarcel

**Closed** 2017-05-30 11:08 UTC
