### ISSUE TITLE
NODATA_PIXEL_PERCENTAGE 

### ISSUE THREAD

**Issue by lvhengani** [sentinelsat/sentinelsat#205] opened 2018-06-14 11:43 UTC
On the retreived full metadata metadata dictionary, the information for `NODATA_PIXEL_PERCENTAGE ` is omitted. Is it possible to include it in the next version?

**Comment by valgur** [comment] 2018-06-14 15:41
Unfortunately, that field is simply not provided on the server side, so there is nothing that can be done in sentinelsat to improve on this. Besides, sentinelsat always returns each and every field that is provided on the server anyway.
I encourage you to get in touch with Data Hub's support regarding this improvement idea.

There is also some existing discussion regarding this on the STEP forum: https://forum.step.esa.int/t/searching-for-s-2-images-with-nodata-pixel-percentage/8317
https://forum.step.esa.int/t/metadata-for-sentinel2/8169

**Comment by valgur** [comment] 2018-06-14 16:47
Actually, since the information *is* included in the metadata inside the product archive files in `MTD_MSIL2A.xml` and the Data Hub's OData API allows such individual files to be fetched from the archive files, you actually can retrieve this field and filter based on it, if you are really keen on it.

Here's a sample script that does just that:
```python
from sentinelsat import SentinelAPI
from xml.etree import ElementTree as ET

api = SentinelAPI('user', 'password')

# Query a single arbitrary product just so we have something to test with
products = api.query(raw='S2A_MSIL2A_20180614T084601_N0208_R107_T35SPB_20180614T120207')

def get_odata_file_url(uuid, path):
    odata_path = api.api_url + "odata/v1/Products('{}')".format(uuid)
    for p in path.split('/'):
        odata_path += "/Nodes('{}')".format(p)
    odata_path += '/$value'
    return odata_path

def fetch_s2_qi_info(uuid, product_name):
    path = '{}.SAFE/MTD_MSIL2A.xml'.format(product_name)
    url = get_odata_file_url(uuid, path)
    response = api.session.get(url)
    xml = ET.XML(response.content)
    qi_info = {}
    for elem in xml.find('.//Image_Content_QI'):
        qi_info[elem.tag] = float(elem.text)
    return qi_info

filtered = []
for uuid, metadata in products.items():
    qi_info = fetch_s2_qi_info(uuid, metadata['title'])
    if qi_info['NODATA_PIXEL_PERCENTAGE'] < 10:
        filtered.append(uuid)
```

This use case is probably a bit too specific to be included in sentinelsat, though, but we could consider adding a convenience function for the fetching of single files from product archives perhaps.

**Comment by j08lue** [comment] 2018-06-14 18:41
Nice solution, @valgur! 

> we could consider adding a convenience function for the fetching of single files from product archives

I needed that several times already. It would be quite nice to integrate that with the API, since you need to send the request through the API (or another authenticated session) anyways. 

We could maybe add cases for `MTD_MSIL2A.xml` , `MTD_MSIL1C.xml` and return the XML string (`response.content`), like

```python

def _get_processing_level(metadata):
    try:
        return re.search(r'(MSIL[0-9][A-Z])', metadata['title']).group(1)
    except AttributeError:
        raise ValueError('Unable to get processing level from metadata.')

def _get_odata_file_url(metadata, path):
    odata_path = metadata['link'].rstrip('/value$')
    for p in path.split('/'):
        odata_path += "/Nodes('{}')".format(p)
    odata_path += '/$value'
    return odata_path

def fetch_product_mtd(self, uuid, metadata):
    level = _get_processing_level(metadata)
    path = '{}.SAFE/MTD_{}.xml'.format(metadata['title'], level)
    url = _get_odata_file_url(metadata, path)
    response = self.session.get(url)
    return response.content
```

Ideally, DHuS should include the metadata file links in their response. Maybe we should ask them?

To get `MTD_TL.xml` would be really nice, too, but that is a bit more tricky, because we currently do not get the granule identifier / folder name from DHuS but would have to parse the `MTD_L1C.xml` or `MTD_L2A.xml`. Also something DHuS should return to make life a lot easier for us...

**Comment by lvhengani** [comment] 2018-06-19 16:00
Thanks @valgur and @j08lue. I have tried the solution you provided and it works. Ideally they should provide these to avoid searching or retriving data from their systems more than once.

**Comment by Fernerkundung** [comment] 2018-06-20 12:20
Closing, because the issue is solved.

Feel free to keep the discussion going about the improvement idea of fetching single files from the archives or continue in a new Issue (ideally with more descriptive name).

**Closed by Fernerkundung** 2018-06-20 12:20 UTC
