### ISSUE TITLE
--footprints parameter produces incorrect number of footprints for S-1 OCN L2 WV product

### ISSUE THREAD

**Issue by salman451** [sentinelsat/sentinelsat#252] opened 2018-11-29 00:04 UTC
The --footprint parameter produces the search_footprints.geojson file. When querying S-1 L2 OCN WV data each .zip file has a number of NetCDF files corresponding to many WV mode acquisitions, but the geojson file produced using the --footprint parameter creates only one footprint for each .zip file - this is misleading.

**Comment by j08lue** [comment] 2018-11-29 07:10
Can you post example parameters search for these data, please?

The footprint polygons are taken from the metadata we get from DHuS, though. So unless the metadat for these products contain per-acquisition footprints, too, we cannot access them (easily enough). We might be able to help you find a different solution, though.

**Comment by salman451** [comment] 2018-12-05 05:57
Apologies for late reply - I am a new user and I thought Git would send me an email in case someone replied. Anyway, here is a sample query for these types of datasets:

sentinelsat -u [username] -p [password] --sentinel 1 --producttype OCN -s 20181127 -e 20181128 -q "sensoroperationalmode=WV" --footprints

This will return 72 products, and therefore because of the bug the geojson file will only have 72 footprints although in reality each of these 72 products comprises multiple (50-100 or more) .NetCDF files (inside the [filname].SAFE/measurement folder), each representing a footprint. Do you use preview/map-overlay.kml to build the .geojson file, that should contain the correct footprints for all NetCDF files within a .SAFE product.

**Comment by j08lue** [comment] 2018-12-05 11:52
Thanks, I will look into it.

> Do you use preview/map-overlay.kml to build the .geojson file

No, we do not download any files from the product, just parse the metadata from DHuS.

**Comment by Fernerkundung** [comment] 2018-12-06 10:03
Specifically, we are parsing the footprint of the **product**, as delivered by the Copernicus Open Access Hub (or other DHuS). A **product** can consist of multiple **measurements**, which is the case here but also for old Sentinel-2 acquisitions and some Sentinel-3 products.

This becomes clearer, when you look at the metadata of a single product: [S1A_WV_OCN__2SSV_20181128T223437_20181128T225003_024794_02BAAD_95E2](https://scihub.copernicus.eu/dhus/odata/v1/Products('69b3b102-4fda-4762-bc91-1130eb672563')/)

It lists as the footprint:
```
<gml:Polygon srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" xmlns:gml="http://www.opengis.net/gml"> <gml:outerBoundaryIs> <gml:LinearRing> <gml:coordinates>-9.669604,107.707344 -9.628628,107.521477 -9.448086,107.561035 -9.489015,107.746742 -9.669604,107.707344</gml:coordinates> </gml:LinearRing> </gml:outerBoundaryIs> </gml:Polygon>
```

The footprints of each measurement are not listed in the metadata and therefore can't be parsed. This is a limitation of the API (and to some extent the WV product specification, as the footprints of the measurements are not included in the .SAFE file either).

What worries me more is that your search results in 72 products, whereas when I perform a search with the same parameters on scihub I get 140 products. Can you confirm that your search still returns 72 products?

```
( beginPosition:[2018-11-27T00:00:00.000Z TO 2018-11-28T23:59:59.999Z] AND endPosition:[2018-11-27T00:00:00.000Z TO 2018-11-28T23:59:59.999Z] ) AND ( (platformname:Sentinel-1 AND producttype:OCN AND sensoroperationalmode:WV))
```

**Comment by salman451** [comment] 2018-12-12 05:32
Yes, I am still getting 72 products but I am using -s and -e parameters as above in my query not the beginPosition and endPosition parameters as in your query.

**Comment by valgur** [comment] 2020-07-25 09:46
Appears to be a duplicate of #387.

**Closed by valgur** 2020-07-25 09:46 UTC
Labels: question
